---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "casoestudio"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "casoestudio"
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: "casoestudio"
    spec:
      containers:
      - name: "casoestudio"
        image: "gcr.io/taller-stefanini/casoestudio:latest"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 20m
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "casoestudio"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "hello-app"
